[package]
name = "borrow-checker"
version = "0.1.0"
edition = "2024"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
askama = "0.15"
dirs = "5.0"
git2 = { version = "0.20.3", features = ["ssh", "https"] }
log = "0.4"
rand = "0.8"
rational = {version = "1.8", features = ["serde"] }
serde = "1"
serde_json = "1.0"
ssh-key = { version = "0.6", features = ["std", "ed25519", "rand_core"] }
tauri = { version = "2.9.5", features = [] }
tauri-plugin-log = "2"
toml = "0.9"
uuid = { version = "1", features = ["serde", "v4"] }
openssl-sys = { version = "0.9", features = ["vendored"] }

[dev-dependencies]
test-context = "0.5"

[lints.clippy]
unwrap_used = "warn"
