name: Rust

on:
  push:
    branches: [ "main", "gh_action" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - name: Restore cache
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Tauri
      run: cargo install tauri-cli --version "^2.0" --locked
    - name: Build
      run: cargo tauri build
    - name: Run tests
      run: cargo test
    - name: Init Android build
      run: cargo tauri android init --ci
    - name: Build Android
      run: cargo tauri android build --ci
